---
name: "Setup node for an action"
description: "Setup node package, cache and path for an action"
inputs:
  verdaccio_token:
    description: "Get verdaccio token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Node setup
      uses: actions/setup-node@main
      with:
        cache: "npm"

    - name: Install dependencies
      run: npm ci
      shell: bash
      env:
        VERDACCIO_TOKEN: ${{ inputs.verdaccio_token }}

    - name: Run Tests
      shell: bash
      run: npm run test:coverage
      env:
        VERDACCIO_TOKEN: ${{ inputs.verdaccio_token }}
