---
name: "Setup node for an action"
description: "Setup node package, cache and path for an action"
inputs:
  actionPath:
    description: "calling action path's to setup"

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        cache: 'npm'
    - run: npm ci
      shell: bash
      env:
        VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

    - name: Run Tests
      shell: bash
      run: npm run test:coverage
      env:
        VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
