---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ARGOCD_APP_NAMESPACE | default(CI_PROJECT_NAME)}}
  name: {{CI_PROJECT_NAME}}-vault
  annotations:
    avp.kubernetes.io/path: {{ENVIRONMENT}}/data/{{CI_PROJECT_NAME}}
type: Opaque
stringData:
