---
# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      # We just added another step and the relative path of the custom action
      - name: Load & Cache Dependencies
        uses: estudosdevops/actions/util-setup-node@main

      - name: Run Unit Tests
        run: npm run test:coverage

# name: "Run Unit Tests"

# on:
#   push:
#     branches:
#       - main

# jobs:
#   Unit-Tests:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@main
#       - uses: actions/setup-node@main
#         with:
#           node-version: 18
#       - run: npm ci
#       # - run: npm run test:coverage
#         env:
#           VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
