---
# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Tests
      uses: ./actions/util-setup-node
