---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  test-units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - run: npm ci
      # - run: npm run test:coverage
        env:
          VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}