---
# name: Test

# on: [push]

# jobs:
#   test-unit:
#     runs-on: ubuntu-latest
#     name: Run Unit Tests
#     steps:
#       - uses: actions/checkout@main
#       - uses: chill-viking/npm-ci@latest


name: Test

on:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - run: npm ci
      # - run: npx semantic-release
        env:
          VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}