---
name: Test

on: [push]

runs:
  using: "composite"
  steps:

  - name: Checkout repository
    uses: actions/checkout@main

  # - name: Install dependencies
  #   uses: chill-viking/npm-ci@latest
