---
# .github/workflows/main.yml
name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@main
      - uses: estudosdevops/actions/util-setup-node@main
        with:
          verdaccio_token: ${{ secrets.VERDACCIO_TOKEN }}
