---
name: Test

on: [push]

steps:
  - uses: actions/checkout@main
    name: Checkout repository

  - uses: chill-viking/npm-ci@latest
    name: Install dependencies
    with:
      working_directory: './npm-root-folder/'