---
name: Test

on: [push]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@main

  # - name: Install dependencies
  #   uses: chill-viking/npm-ci@latest
