---
name: 😎 PreProd

on:
  push:
    branches:
      - '**'

jobs:
  build-image:
    name:  Build & Register image
    runs-on: ubuntu-latest
    steps:

      - name: Use autodevops build and register
        uses: ./actions/build-image
        with:
          project: "sample-app"
          imageName: sample-app/api
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerbuildargs: |
            NODE_ENV=production
            VERDACCIO_TOKEN=${{ secrets.VERDACCIO_TOKEN }}
          environment: "preprod"
