---
name: 🔖 Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 20
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
          GIT_AUTHOR_EMAIL: ${{ secrets.ESTUDOSDEVOPSBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.ESTUDOSDEVOPSBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.ESTUDOSDEVOPSBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.ESTUDOSDEVOPSBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
