---
name: 🔖 Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        semantic_version: 20
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
      env:
          GIT_AUTHOR_EMAIL: ${{ secrets.ESTUDOSDEVOPSBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.ESTUDOSDEVOPSBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.ESTUDOSDEVOPSBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.ESTUDOSDEVOPSBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push updates to branch for major version
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git :refs/tags/v${{steps.semantic.outputs.new_release_major_version}}
        git tag -f v${{steps.semantic.outputs.new_release_major_version}}
        git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git v${{steps.semantic.outputs.new_release_major_version}}
      env:
        GITHUB_TOKEN: ${{ secrets.ESTUDOSDEVOPSBOT_BOTO_PAT }}
