---
name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: ./actions/unit-tests
        with:
          verdaccio_token: ${{ secrets.VERDACCIO_TOKEN }}

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Run Scan
        uses: sonarsource/sonarqube-scan-action@master
        # with:
        #   args: >
        #     -Dsonar.projectKey="$CI_PROJECT_NAME"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # build-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: SocialGouv/actions/autodevops-build-register@v1
  #     with:
  #       project: "sample-app"
  #       imageName: sample-app/api
  #       token: ${{ secrets.GITHUB_TOKEN }}

  #       # dockerfile: "/path/to/Dockerfile" # optional
  #       # dockercontext: "/path/to/content" # optional
  #       # dockerbuildargs: | # optional
  #       #   NODE_ENV=production
  #       # environment: "preprod" # optional
